services:
  webserver:
    image: nginx:alpine
    container_name: rock-paper-webserver
    working_dir: /application
    volumes:
      - .:/application:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "11001:80"

  node:
    build: docker/node
    container_name: rock-paper-node
    command: ["docker/node/entrypoint.sh"]
    working_dir: /application
    volumes:
      - .:/application:cached